import type { Complaint } from "./types";
import { clusterKey } from "./utils";

function hoursAgo(h: number) {
  return new Date(Date.now() - h * 36e5).toISOString();
}
function hoursFromNow(h: number) {
  return new Date(Date.now() + h * 36e5).toISOString();
}

// Real photo evidence, bundled under /public/evidence and served as static assets.
// Keeps the demo realistic without any live uploads. See public/evidence/*.jpg.
const EVIDENCE: Record<string, { before?: string; after?: string }> = {
  "CL-240817-1102": { before: "/evidence/pothole.jpg" }, // pothole · MP Nagar
  "CL-240817-2210": { before: "/evidence/water-tanker.jpg" }, // no water · Arera Colony
  "CL-240817-3044": { before: "/evidence/streetlight.jpg" }, // dark road · Kolar
  "CL-240817-4091": { before: "/evidence/garbage.jpg" }, // garbage pile · Shahpura
  "CL-240817-6612": { before: "/evidence/manhole.jpg" }, // open manhole · Habibganj
  "CL-240817-7720": { before: "/evidence/transformer.jpg" }, // sparking transformer · New Market
  "CL-240816-0881": { before: "/evidence/flood.jpg" }, // nala overflow · Indrapuri
  "CL-240816-0199": { before: "/evidence/playground.jpg" }, // park · Bairagarh
  "CL-240815-3001": {
    before: "/evidence/footpath.jpg", // broken footpath tiles
    after: "/evidence/road-fixed.jpg", // resurfaced
  },
};

export function seedComplaints(): Complaint[] {
  const rows: Array<Omit<Complaint, "clusterId" | "impactCount" | "voters" | "resolutionImageDataUrl"> & { voters?: string[] }> = [
    {
      id: "CL-240817-1102",
      citizenId: "c-meena",
      citizenName: "Meena Sharma",
      phone: "+91 98260 44112",
      anonymous: false,
      channel: "text",
      originalText:
        "Huge pothole on the MP Nagar Zone 2 main road near DB Mall signal. Two bikes already skidded this morning. Please fix before someone gets badly hurt.",
      language: "en",
      languageName: "English",
      translatedText:
        "Huge pothole on the MP Nagar Zone 2 main road near DB Mall signal. Two bikes already skidded this morning. Please fix before someone gets badly hurt.",
      summary: "Deep pothole at MP Nagar Zone 2 / DB Mall signal causing bike skids.",
      imageDataUrl: null,
      lat: 23.2332,
      lng: 77.4343,
      locationLabel: "MP Nagar Zone 2, near DB Mall",
      ward: "Ward 12 — MP Nagar",
      category: "roads",
      department: "Public Works — Roads",
      departmentCode: "PWD",
      officer: "R. Sharma",
      priority: "high",
      severity: 8,
      sentiment: "distress",
      confidence: 0.93,
      reasoning: "Explicit pothole + injury risk at a named junction. PWD roads, high because of reported accidents.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursFromNow(11),
      status: "assigned",
      duplicateOf: null,
      upvotes: 47,
      verifiedByHuman: true,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(18),
      updatedAt: hoursAgo(4),
      timeline: [
        { at: hoursAgo(18), label: "Filed via web portal", actor: "Meena Sharma", kind: "citizen" },
        { at: hoursAgo(18), label: "Classified → Roads / PWD · confidence 93%", actor: "CivicLens AI", kind: "ai" },
        { at: hoursAgo(16), label: "Officer verified classification", actor: "R. Sharma", kind: "officer" },
        { at: hoursAgo(4), label: "Assigned to ward PWD gang", actor: "R. Sharma", kind: "officer" },
      ],
    },
    {
      id: "CL-240817-1188",
      citizenId: "c-rahul",
      citizenName: "Rahul Jain",
      phone: "+91 90000 11223",
      anonymous: false,
      channel: "whatsapp",
      originalText: "Same pothole near DB Mall MP Nagar, even worse after last night rain. Cars are swerving into the other lane.",
      language: "en",
      languageName: "English",
      translatedText: "Same pothole near DB Mall MP Nagar, even worse after last night rain. Cars are swerving into the other lane.",
      summary: "Duplicate report of DB Mall / MP Nagar pothole after rain.",
      imageDataUrl: null,
      lat: 23.2335,
      lng: 77.4341,
      locationLabel: "MP Nagar Zone 2, near DB Mall",
      ward: "Ward 12 — MP Nagar",
      category: "roads",
      department: "Public Works — Roads",
      departmentCode: "PWD",
      officer: "R. Sharma",
      priority: "high",
      severity: 8,
      sentiment: "anger",
      confidence: 0.91,
      reasoning: "Same landmark and issue as CL-240817-1102. Merged as Me Too / duplicate.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursFromNow(11),
      status: "queued",
      duplicateOf: "CL-240817-1102",
      upvotes: 0,
      verifiedByHuman: false,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(6),
      updatedAt: hoursAgo(6),
      timeline: [
        { at: hoursAgo(6), label: "Filed via WhatsApp", actor: "Rahul Jain", kind: "citizen" },
        { at: hoursAgo(6), label: "Detected duplicate of CL-240817-1102 · clustered", actor: "CivicLens AI", kind: "ai" },
      ],
    },
    {
      id: "CL-240817-2210",
      citizenId: "c-kavita",
      citizenName: "कविता यादव",
      phone: "+91 97550 33445",
      anonymous: false,
      channel: "voice",
      originalText:
        "तीन दिन से वार्ड 18 अरेरा कॉलोनी में पानी बिल्कुल नहीं आ रहा है। टैंकर भी नहीं भेजा। बच्चों के लिए पीने का पानी नहीं है।",
      language: "hi",
      languageName: "Hindi",
      translatedText:
        "No water in Ward 18 Arera Colony for three days. No tanker either. There is no drinking water for the children.",
      summary: "Three-day water outage in Arera Colony; tanker not sent.",
      imageDataUrl: null,
      lat: 23.2156,
      lng: 77.4358,
      locationLabel: "Arera Colony E-7",
      ward: "Ward 18 — Arera Colony",
      category: "water",
      department: "Public Health Engineering — Water",
      departmentCode: "WTR",
      officer: "A. Khan",
      priority: "urgent",
      severity: 9,
      sentiment: "distress",
      confidence: 0.96,
      reasoning: "Multi-day drinking-water outage affecting children. PHE water, urgent.",
      isEmergency: true,
      slaHours: 4,
      slaDueAt: hoursAgo(2),
      status: "in_progress",
      duplicateOf: null,
      upvotes: 22,
      verifiedByHuman: true,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(9),
      updatedAt: hoursAgo(1),
      timeline: [
        { at: hoursAgo(9), label: "Voice complaint transcribed", actor: "कविता यादव", kind: "citizen" },
        { at: hoursAgo(9), label: "hi → en · Water / PHE · urgent · 96%", actor: "CivicLens AI", kind: "ai" },
        { at: hoursAgo(8), label: "SLA clock started (4h)", actor: "System", kind: "system" },
        { at: hoursAgo(3), label: "Tanker requested from Kotra depot", actor: "A. Khan", kind: "officer" },
        { at: hoursAgo(1), label: "SLA breach predicted — still open", actor: "System", kind: "system" },
      ],
    },
    {
      id: "CL-240817-3044",
      citizenId: "c-imran",
      citizenName: "Imran Qureshi",
      phone: "+91 88899 22110",
      anonymous: false,
      channel: "image",
      originalText: "Street light dead for a week, pitch dark stretch on Kolar road near Sagar Estate. Women returning from shift work are scared.",
      language: "en",
      languageName: "English",
      translatedText: "Street light dead for a week, pitch dark stretch on Kolar road near Sagar Estate. Women returning from shift work are scared.",
      summary: "Dark stretch on Kolar Road near Sagar Estate — street light out a week.",
      imageDataUrl: null,
      lat: 23.1744,
      lng: 77.4162,
      locationLabel: "Kolar Road, Sagar Estate",
      ward: "Ward 31 — Kolar",
      category: "electricity",
      department: "Electrical & Street Lighting",
      departmentCode: "ELC",
      officer: "P. Verma",
      priority: "high",
      severity: 7,
      sentiment: "distress",
      confidence: 0.88,
      reasoning: "Street lighting failure plus safety concern for night workers. Electrical dept.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursFromNow(8),
      status: "queued",
      duplicateOf: null,
      upvotes: 11,
      verifiedByHuman: false,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(16),
      updatedAt: hoursAgo(16),
      timeline: [
        { at: hoursAgo(16), label: "Photo complaint filed", actor: "Imran Qureshi", kind: "citizen" },
        { at: hoursAgo(16), label: "Classified → Electricity · 88%", actor: "CivicLens AI", kind: "ai" },
      ],
    },
    {
      id: "CL-240817-4091",
      citizenId: "c-priya",
      citizenName: "Priya Nair",
      phone: "+91 70123 88990",
      anonymous: false,
      channel: "text",
      originalText: "Garbage mountain behind the Shahpura lake park hasn't been lifted in 11 days. Dogs have torn the bags. Smell is unbearable.",
      language: "en",
      languageName: "English",
      translatedText: "Garbage mountain behind the Shahpura lake park hasn't been lifted in 11 days. Dogs have torn the bags. Smell is unbearable.",
      summary: "Uncollected garbage pile behind Shahpura lake park for 11 days.",
      imageDataUrl: null,
      lat: 23.2031,
      lng: 77.4249,
      locationLabel: "Shahpura Lake park rear",
      ward: "Ward 42 — Shahpura",
      category: "sanitation",
      department: "Health & Sanitation",
      departmentCode: "SAN",
      officer: "S. Iyer",
      priority: "high",
      severity: 7,
      sentiment: "anger",
      confidence: 0.94,
      reasoning: "Prolonged uncollected waste at a public park. Sanitation, high health risk.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursFromNow(3),
      status: "assigned",
      duplicateOf: null,
      upvotes: 31,
      verifiedByHuman: true,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(21),
      updatedAt: hoursAgo(5),
      timeline: [
        { at: hoursAgo(21), label: "Filed via web portal", actor: "Priya Nair", kind: "citizen" },
        { at: hoursAgo(21), label: "Classified → Sanitation · 94%", actor: "CivicLens AI", kind: "ai" },
        { at: hoursAgo(5), label: "Assigned to ward sanitation crew", actor: "S. Iyer", kind: "officer" },
      ],
    },
    {
      id: "CL-240817-4099",
      citizenId: "c-arjun",
      citizenName: "Arjun Malhotra",
      phone: "+91 98111 22334",
      anonymous: false,
      channel: "whatsapp",
      originalText: "Same dump at Shahpura lake. Please send the truck. 31 people already flagged this.",
      language: "en",
      languageName: "English",
      translatedText: "Same dump at Shahpura lake. Please send the truck. 31 people already flagged this.",
      summary: "Me Too on Shahpura lake garbage pile.",
      imageDataUrl: null,
      lat: 23.203,
      lng: 77.425,
      locationLabel: "Shahpura Lake park rear",
      ward: "Ward 42 — Shahpura",
      category: "sanitation",
      department: "Health & Sanitation",
      departmentCode: "SAN",
      officer: "S. Iyer",
      priority: "high",
      severity: 7,
      sentiment: "anger",
      confidence: 0.9,
      reasoning: "Same site as CL-240817-4091.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursFromNow(3),
      status: "queued",
      duplicateOf: "CL-240817-4091",
      upvotes: 0,
      verifiedByHuman: false,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(3),
      updatedAt: hoursAgo(3),
      timeline: [
        { at: hoursAgo(3), label: "Filed via WhatsApp", actor: "Arjun Malhotra", kind: "citizen" },
        { at: hoursAgo(3), label: "Duplicate of CL-240817-4091", actor: "CivicLens AI", kind: "ai" },
      ],
    },
    {
      id: "CL-240817-5501",
      citizenId: "anon-7f3",
      citizenName: "Anonymous",
      phone: null,
      anonymous: true,
      channel: "text",
      originalText:
        "Ward office clerk at TT Nagar demanding ₹2,000 extra to process a death certificate. I have a tracking token only. Please don't call me.",
      language: "en",
      languageName: "English",
      translatedText:
        "Ward office clerk at TT Nagar demanding ₹2,000 extra to process a death certificate. I have a tracking token only. Please don't call me.",
      summary: "Alleged bribe demand at TT Nagar ward office for a death certificate.",
      imageDataUrl: null,
      lat: 23.2339,
      lng: 77.4012,
      locationLabel: "TT Nagar ward office",
      ward: "Ward 23 — TT Nagar",
      category: "corruption",
      department: "Vigilance Cell",
      departmentCode: "VIG",
      officer: "Duty Officer — Vigilance",
      priority: "high",
      severity: 8,
      sentiment: "distress",
      confidence: 0.81,
      reasoning: "Named location + alleged illegal fee. Routed to Vigilance. Identity withheld.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursFromNow(19),
      status: "received",
      duplicateOf: null,
      upvotes: 0,
      verifiedByHuman: false,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(5),
      updatedAt: hoursAgo(5),
      timeline: [
        { at: hoursAgo(5), label: "Anonymous whistleblower filing (token only)", actor: "Anonymous", kind: "citizen" },
        { at: hoursAgo(5), label: "Classified → Vigilance · 81% · PII stripped", actor: "CivicLens AI", kind: "ai" },
      ],
    },
    {
      id: "CL-240817-6612",
      citizenId: "c-selvi",
      citizenName: "Selvi Murugan",
      phone: "+91 94440 77881",
      anonymous: false,
      channel: "text",
      originalText: "ஹபிப்கஞ்ச் ரயில் நிலையம் அருகில் திறந்த மான்கோல். குழந்தைகள் விளையாடும் இடம். உடனே மூடவும்.",
      language: "ta",
      languageName: "Tamil",
      translatedText: "Open manhole near Habibganj railway station. Children play in this area. Please cover it immediately.",
      summary: "Open manhole near Habibganj station — children at risk.",
      imageDataUrl: null,
      lat: 23.2211,
      lng: 77.4399,
      locationLabel: "Habibganj station approach",
      ward: "Ward 51 — Habibganj",
      category: "roads",
      department: "Public Works — Roads",
      departmentCode: "PWD",
      officer: "D. Gupta",
      priority: "urgent",
      severity: 10,
      sentiment: "distress",
      confidence: 0.97,
      reasoning: "Open manhole + children. Immediate physical danger. Tamil intake translated.",
      isEmergency: true,
      slaHours: 4,
      slaDueAt: hoursFromNow(1.5),
      status: "assigned",
      duplicateOf: null,
      upvotes: 8,
      verifiedByHuman: true,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(2.4),
      updatedAt: hoursAgo(0.7),
      timeline: [
        { at: hoursAgo(2.4), label: "Filed via web portal (Tamil)", actor: "Selvi Murugan", kind: "citizen" },
        { at: hoursAgo(2.4), label: "ta → en · Roads · URGENT · 97%", actor: "CivicLens AI", kind: "ai" },
        { at: hoursAgo(0.7), label: "Barricade crew dispatched", actor: "D. Gupta", kind: "officer" },
      ],
    },
    {
      id: "CL-240816-0199",
      citizenId: "c-farah",
      citizenName: "Farah Ansari",
      phone: "+91 91234 55667",
      anonymous: false,
      channel: "text",
      originalText: "Park lights at Bairagarh children's park restored. Thank you — but the broken see-saw is still there.",
      language: "en",
      languageName: "English",
      translatedText: "Park lights at Bairagarh children's park restored. Thank you — but the broken see-saw is still there.",
      summary: "Bairagarh park lights restored; see-saw still broken.",
      imageDataUrl: null,
      lat: 23.267,
      lng: 77.338,
      locationLabel: "Bairagarh children's park",
      ward: "Ward 8 — Bairagarh",
      category: "public_services",
      department: "Public Services & General Admin",
      departmentCode: "PUB",
      officer: "L. Rao",
      priority: "low",
      severity: 3,
      sentiment: "hopeful",
      confidence: 0.74,
      reasoning: "Follow-up on a park amenity. Public services, low urgency.",
      isEmergency: false,
      slaHours: 168,
      slaDueAt: hoursFromNow(90),
      status: "resolved",
      duplicateOf: null,
      upvotes: 4,
      verifiedByHuman: true,
      overrideNotes: null,
      feedbackRating: 4,
      createdAt: hoursAgo(40),
      updatedAt: hoursAgo(12),
      timeline: [
        { at: hoursAgo(40), label: "Filed via web portal", actor: "Farah Ansari", kind: "citizen" },
        { at: hoursAgo(30), label: "Electrical crew fixed lights", actor: "P. Verma", kind: "officer" },
        { at: hoursAgo(12), label: "Marked resolved — see-saw logged as new job", actor: "L. Rao", kind: "officer" },
        { at: hoursAgo(11), label: "Citizen rated 4/5", actor: "Farah Ansari", kind: "citizen" },
      ],
    },
    {
      id: "CL-240816-0881",
      citizenId: "c-vikas",
      citizenName: "Vikas Sahu",
      phone: "+91 99810 66778",
      anonymous: false,
      channel: "voice",
      originalText: "Overflowing nala on Ayodhya Bypass near Indrapuri. Water entering ground-floor shops every afternoon.",
      language: "en",
      languageName: "English",
      translatedText: "Overflowing nala on Ayodhya Bypass near Indrapuri. Water entering ground-floor shops every afternoon.",
      summary: "Nala overflow on Ayodhya Bypass flooding Indrapuri shops.",
      imageDataUrl: null,
      lat: 23.259,
      lng: 77.463,
      locationLabel: "Ayodhya Bypass, Indrapuri",
      ward: "Ward 51 — Habibganj",
      category: "sanitation",
      department: "Health & Sanitation",
      departmentCode: "SAN",
      officer: "K. Patel",
      priority: "high",
      severity: 8,
      sentiment: "anger",
      confidence: 0.89,
      reasoning: "Drainage overflow damaging shops daily. Sanitation / drainage.",
      isEmergency: false,
      slaHours: 24,
      slaDueAt: hoursAgo(6),
      status: "in_progress",
      duplicateOf: null,
      upvotes: 15,
      verifiedByHuman: false,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(30),
      updatedAt: hoursAgo(7),
      timeline: [
        { at: hoursAgo(30), label: "Voice complaint transcribed", actor: "Vikas Sahu", kind: "citizen" },
        { at: hoursAgo(30), label: "Classified → Sanitation · 89%", actor: "CivicLens AI", kind: "ai" },
        { at: hoursAgo(7), label: "Jetting machine scheduled", actor: "K. Patel", kind: "officer" },
      ],
    },
    {
      id: "CL-240817-7720",
      citizenId: "c-neha",
      citizenName: "Neha Chouhan",
      phone: "+91 88777 33445",
      anonymous: false,
      channel: "text",
      originalText: "Transformer humming very loud and sparking at New Market, TT Nagar. People are standing away. Looks dangerous.",
      language: "en",
      languageName: "English",
      translatedText: "Transformer humming very loud and sparking at New Market, TT Nagar. People are standing away. Looks dangerous.",
      summary: "Sparking transformer at New Market, TT Nagar.",
      imageDataUrl: null,
      lat: 23.2366,
      lng: 77.4001,
      locationLabel: "New Market, TT Nagar",
      ward: "Ward 23 — TT Nagar",
      category: "electricity",
      department: "Electrical & Street Lighting",
      departmentCode: "ELC",
      officer: "N. Joshi",
      priority: "urgent",
      severity: 9,
      sentiment: "distress",
      confidence: 0.95,
      reasoning: "Sparking transformer in a crowded market. Treat as live electrical hazard.",
      isEmergency: true,
      slaHours: 4,
      slaDueAt: hoursFromNow(2.2),
      status: "received",
      duplicateOf: null,
      upvotes: 6,
      verifiedByHuman: false,
      overrideNotes: null,
      feedbackRating: null,
      createdAt: hoursAgo(1.8),
      updatedAt: hoursAgo(1.8),
      timeline: [
        { at: hoursAgo(1.8), label: "Filed via web portal", actor: "Neha Chouhan", kind: "citizen" },
        { at: hoursAgo(1.8), label: "Classified → Electricity · URGENT · 95%", actor: "CivicLens AI", kind: "ai" },
      ],
    },
    {
      id: "CL-240815-3001",
      citizenId: "c-meena",
      citizenName: "Meena Sharma",
      phone: "+91 98260 44112",
      anonymous: false,
      channel: "text",
      originalText: "Broken footpath tiles outside BMC office, TT Nagar. Elderly people are tripping.",
      language: "en",
      languageName: "English",
      translatedText: "Broken footpath tiles outside BMC office, TT Nagar. Elderly people are tripping.",
      summary: "Broken footpath tiles outside BMC office.",
      imageDataUrl: null,
      lat: 23.2344,
      lng: 77.4022,
      locationLabel: "Outside BMC office, TT Nagar",
      ward: "Ward 23 — TT Nagar",
      category: "roads",
      department: "Public Works — Roads",
      departmentCode: "PWD",
      officer: "R. Sharma",
      priority: "medium",
      severity: 5,
      sentiment: "neutral",
      confidence: 0.86,
      reasoning: "Footpath defect causing trip hazard. Medium — not an outage, but injury risk.",
      isEmergency: false,
      slaHours: 72,
      slaDueAt: hoursAgo(10),
      status: "resolved",
      duplicateOf: null,
      upvotes: 9,
      verifiedByHuman: true,
      overrideNotes: null,
      feedbackRating: 5,
      createdAt: hoursAgo(82),
      updatedAt: hoursAgo(20),
      timeline: [
        { at: hoursAgo(82), label: "Filed via web portal", actor: "Meena Sharma", kind: "citizen" },
        { at: hoursAgo(50), label: "Work order issued", actor: "R. Sharma", kind: "officer" },
        { at: hoursAgo(20), label: "Tiles replaced — resolved", actor: "R. Sharma", kind: "officer" },
        { at: hoursAgo(19), label: "Citizen rated 5/5 · impact: 9 neighbours", actor: "Meena Sharma", kind: "citizen" },
      ],
    },
  ];

  return rows.map((r) => {
    const clusterId = r.duplicateOf
      ? clusterKey(
          rows.find((x) => x.id === r.duplicateOf)?.category ?? r.category,
          r.ward,
          r.locationLabel,
        )
      : clusterKey(r.category, r.ward, r.locationLabel);
    const related = rows.filter((x) => {
      const key = x.duplicateOf
        ? clusterKey(
            rows.find((y) => y.id === x.duplicateOf)?.category ?? x.category,
            x.ward,
            x.locationLabel,
          )
        : clusterKey(x.category, x.ward, x.locationLabel);
      return key === clusterId;
    });
    const master = related.find((x) => !x.duplicateOf) ?? r;
    const ev = EVIDENCE[r.id];
    return {
      ...r,
      imageDataUrl: ev?.before ?? r.imageDataUrl,
      resolutionImageDataUrl: ev?.after ?? null,
      voters: r.voters ?? [],
      clusterId,
      impactCount: (master.upvotes ?? 0) + related.length,
    };
  });
}
